/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MPKCKeys"
 * 	found in "keys.asn1"
 */

#ifndef	_MPKCSignature_H_
#define	_MPKCSignature_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MPKCSignature */
typedef struct MPKCSignature {
	IA5String_t	 version;
	IA5String_t	 digest;
	OCTET_STRING_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MPKCSignature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MPKCSignature;

#ifdef __cplusplus
}
#endif

#endif	/* _MPKCSignature_H_ */
#include <asn_internal.h>
