/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MPKCKeys"
 * 	found in "keys.asn1"
 */

#ifndef	_MPKCPublicKey_H_
#define	_MPKCPublicKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MPKCPublicKey */
typedef struct MPKCPublicKey {
	IA5String_t	 version;
	OCTET_STRING_t	 key;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MPKCPublicKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MPKCPublicKey;

#ifdef __cplusplus
}
#endif

#endif	/* _MPKCPublicKey_H_ */
#include <asn_internal.h>
